<?php

/*
 |--------------------------------------------------------------------------
 | DO NOT EDIT THIS FILE DIRECTLY.
 |--------------------------------------------------------------------------
*/

return [

    'Superuser' => [
        [
            'permission' => 'superuser',
            'display' => true,
        ],
    ],

    'Admin' => [
        [
            'permission' => 'admin',
            'display' => true,
        ],
    ],

    'Import' => [
        [
            'permission' => 'import',
            'display' => true,
        ],
    ],

    'Reports' => [
        [
            'permission' => 'reports.view',
            'display' => true,
        ],
    ],

    'Assets' => [
        [
            'permission' => 'assets.view',
            'display' => true,
        ],
        [
            'permission' => 'assets.create',
            'display' => true,
        ],
        [
            'permission' => 'assets.edit',
            'display' => true,
        ],
        [
            'permission' => 'assets.delete',
            'display' => true,
        ],
        [
            'permission' => 'assets.checkout',
            'display' => false,
        ],

        [
            'permission' => 'assets.checkin',
            'display' => true,
        ],

        [
            'permission' => 'assets.checkout',
            'display' => true,
        ],

        [
            'permission' => 'assets.audit',
            'display' => true,
        ],

        [
            'permission' => 'assets.view.requestable',
            'display' => true,
        ],

        [
            'permission' => 'assets.view.encrypted_custom_fields',
            'display' => true,
        ],
        [
            'permission' => 'assets.files',
            'display' => true,
        ],

    ],

    'Accessories' => [
        [
            'permission' => 'accessories.view',
            'display' => true,
        ],
        [
            'permission' => 'accessories.create',
            'display' => true,
        ],
        [
            'permission' => 'accessories.edit',
            'display' => true,
        ],
        [
            'permission' => 'accessories.delete',
            'display' => true,
        ],
        [
            'permission' => 'accessories.checkout',
            'display' => true,
        ],
        [
            'permission' => 'accessories.checkin',
            'display' => true,
        ],
        [
            'permission' => 'accessories.files',
            'display' => true,
        ],

    ],

    'Consumables' => [
        [
            'permission' => 'consumables.view',
            'display' => true,
        ],
        [
            'permission' => 'consumables.create',
            'display' => true,
        ],
        [
            'permission' => 'consumables.edit',
            'display' => true,
        ],
        [
            'permission' => 'consumables.delete',
            'display' => true,
        ],
        [
            'permission' => 'consumables.checkout',
            'display' => true,
        ],
        [
            'permission' => 'consumables.files',
            'display' => true,
        ],
    ],

    'Licenses' => [
        [
            'permission' => 'licenses.view',
            'display' => true,
        ],
        [
            'permission' => 'licenses.create',
            'display' => true,
        ],
        [
            'permission' => 'licenses.edit',
            'display' => true,
        ],
        [
            'permission' => 'licenses.delete',
            'display' => true,
        ],
        [
            'permission' => 'licenses.checkout',
            'display' => true,
        ],
        [
            'permission' => 'licenses.checkin',
            'display' => true,
        ],
        [
            'permission' => 'licenses.keys',
            'display' => true,
        ],
        [
            'permission' => 'licenses.files',
            'display' => true,
        ],
    ],

    'Components' => [
        [
            'permission' => 'components.view',
            'display' => true,
        ],
        [
            'permission' => 'components.create',
            'display' => true,
        ],
        [
            'permission' => 'components.edit',
            'display' => true,
        ],
        [
            'permission' => 'components.delete',
            'display' => true,
        ],
        [
            'permission' => 'components.checkout',
            'display' => true,
        ],
        [
            'permission' => 'components.checkin',
            'display' => true,
        ],
        [
            'permission' => 'components.files',
            'display' => true,
        ],

    ],

    'Kits' => [
        [
            'permission' => 'kits.view',
            'display' => true,
        ],
        [
            'permission' => 'kits.create',
            'display' => true,
        ],
        [
            'permission' => 'kits.edit',
            'display' => true,
        ],
        [
            'permission' => 'kits.delete',
            'display' => true,
        ],
    ],

    'Users' => [
        [
            'permission' => 'users.view',
            'display' => true,
        ],
        [
            'permission' => 'users.create',
            'display' => true,
        ],
        [
            'permission' => 'users.edit',
            'display' => true,
        ],
        [
            'permission' => 'users.delete',
            'display' => true,
        ],
        [
            'permission' => 'users.files',
            'display' => true,
        ],

    ],

    'Models' => [
        [
            'permission' => 'models.view',
            'display' => true,
        ],
        [
            'permission' => 'models.create',
            'display' => true,
        ],
        [
            'permission' => 'models.edit',
            'display' => true,
        ],
        [
            'permission' => 'models.delete',
            'display' => true,
        ],
        [
            'permission' => 'models.files',
            'display' => true,
        ],

    ],

    'Categories' => [
        [
            'permission' => 'categories.view',
            'display' => true,
        ],
        [
            'permission' => 'categories.create',
            'display' => true,
        ],
        [
            'permission' => 'categories.edit',
            'display' => true,
        ],
        [
            'permission' => 'categories.delete',
            'display' => true,
        ],
    ],

    'Departments' => [
        [
            'permission' => 'departments.view',
            'display' => true,
        ],
        [
            'permission' => 'departments.create',
            'display' => true,
        ],
        [
            'permission' => 'departments.edit',
            'display' => true,
        ],
        [
            'permission' => 'departments.delete',
            'display' => true,
        ],
        [
            'permission' => 'departments.files',
            'display' => true,
        ],
    ],

    'Status Labels' => [
        [
            'permission' => 'statuslabels.view',
            'display' => true,
        ],
        [
            'permission' => 'statuslabels.create',
            'display' => true,
        ],
        [
            'permission' => 'statuslabels.edit',
            'display' => true,
        ],
        [
            'permission' => 'statuslabels.delete',
            'display' => true,
        ],
    ],

    'Custom Fields' => [
        [
            'permission' => 'customfields.view',
            'display' => true,
        ],
        [
            'permission' => 'customfields.create',
            'display' => true,
        ],
        [
            'permission' => 'customfields.edit',
            'display' => true,
        ],
        [
            'permission' => 'customfields.delete',
            'display' => true,
        ],
    ],

    'Suppliers' => [
        [
            'permission' => 'suppliers.view',
            'display' => true,
        ],
        [
            'permission' => 'suppliers.create',
            'display' => true,
        ],
        [
            'permission' => 'suppliers.edit',
            'display' => true,
        ],
        [
            'permission' => 'suppliers.delete',
            'display' => true,
        ],
        [
            'permission' => 'suppliers.files',
            'display' => true,
        ],
    ],

    'Manufacturers' => [
        [
            'permission' => 'manufacturers.view',
            'display' => true,
        ],
        [
            'permission' => 'manufacturers.create',
            'display' => true,
        ],
        [
            'permission' => 'manufacturers.edit',
            'display' => true,
        ],
        [
            'permission' => 'manufacturers.delete',
            'display' => true,
        ],
    ],

    'Depreciations' => [
        [
            'permission' => 'depreciations.view',
            'display' => true,
        ],
        [
            'permission' => 'depreciations.create',
            'display' => true,
        ],
        [
            'permission' => 'depreciations.edit',
            'display' => true,
        ],
        [
            'permission' => 'depreciations.delete',
            'display' => true,
        ],
    ],

    'Locations' => [
        [
            'permission' => 'locations.view',
            'display' => true,
        ],
        [
            'permission' => 'locations.create',
            'display' => true,
        ],
        [
            'permission' => 'locations.edit',
            'display' => true,
        ],
        [
            'permission' => 'locations.delete',
            'display' => true,
        ],
        [
            'permission' => 'locations.files',
            'display' => true,
        ],
    ],

    'Companies' => [
        [
            'permission' => 'companies.view',
            'display' => true,
        ],
        [
            'permission' => 'companies.create',
            'display' => true,
        ],
        [
            'permission' => 'companies.edit',
            'display' => true,
        ],
        [
            'permission' => 'companies.delete',
            'display' => true,
        ],
        [
            'permission' => 'companies.files',
            'display' => true,
        ],
    ],

    'User (Self) Accounts' => [
        [
            'permission' => 'self.two_factor',
            'display' => true,
        ],

        [
            'permission' => 'self.api',
            'display' => true,
        ],

        [
            'permission' => 'self.edit_location',
            'display' => true,
        ],

        [
            'permission' => 'self.checkout_assets',
            'display' => true,
        ],

        [
            'permission' => 'self.view_purchase_cost',
            'display' => true,
        ],

    ],

];
