name: "Terraform Plan Pipeline"

#Allow automatic or manual execution when previous pipeline completes
on: 
    workflow_dispatch:
    workflow_run:
        workflows: ["Snipe-IT App Deployment Pipeline"]
        types:
            - completed

#Request OIDC token from GitHub for AWS authentication & allow permission to read repo files
permissions:
    id-token: write 
    contents: read 
 
    
#Global Environment Variables
env:
    AWS_REGION: eu-north-1
    DOMAIN: "tm.zain-amer.co.uk"
    AWS_ROLE_ARN: "arn:aws:iam::954405334747:role/GitHubActions-OIDC-Role"

#Run pipeline on Ubuntu if upstream pipeline succeeeded or triggered manually  
jobs:
    plan-check:
        name: "Terraform Plan Pipeline"
        if: ${{github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
        runs-on: ubuntu-latest

        #Default to working-directory
        defaults:
            run:
                working-directory: ./Terraform
        
        #Download repo code onto runner
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
        
        #The AWS OIDC Authentication bridge
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{env.AWS_ROLE_ARN}}
                role-session-name: terraform-plan
                aws-region: ${{env.AWS_REGION}}
            
            #Install official Hashicorp Terraform 
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
            
            #Verify configuation files have correct spacing, alignment and formatting
            - name: Terraform Lint Check
              run: terraform fmt -check -recursive
            
            #Download required plugins and initialise backend state storage
            - name: Terraform Init
              run: terraform init
            
            #Preview infrastructue that will be created or modified
            - name: Terraform Plan
              run: terraform plan
            
